/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthHomeImport } from './routes/_auth/home'
import { Route as AuthAdminDatabaseImport } from './routes/_auth/admin.database'
import { Route as AuthAdminDatatableTableViewImport } from './routes/_auth/admin.datatable.$table.view'
import { Route as AuthAdminDatatableTableEditImport } from './routes/_auth/admin.datatable.$table.edit'
import { Route as AuthAdminDatatableTableAddImport } from './routes/_auth/admin.datatable.$table.add'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthHomeRoute = AuthHomeImport.update({
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminDatabaseRoute = AuthAdminDatabaseImport.update({
  path: '/admin/database',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminDatatableTableViewRoute =
  AuthAdminDatatableTableViewImport.update({
    path: '/admin/datatable/$table/view',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdminDatatableTableEditRoute =
  AuthAdminDatatableTableEditImport.update({
    path: '/admin/datatable/$table/edit',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdminDatatableTableAddRoute = AuthAdminDatatableTableAddImport.update(
  {
    path: '/admin/datatable/$table/add',
    getParentRoute: () => AuthRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/home': {
      preLoaderRoute: typeof AuthHomeImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/database': {
      preLoaderRoute: typeof AuthAdminDatabaseImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/datatable/$table/add': {
      preLoaderRoute: typeof AuthAdminDatatableTableAddImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/datatable/$table/edit': {
      preLoaderRoute: typeof AuthAdminDatatableTableEditImport
      parentRoute: typeof AuthImport
    }
    '/_auth/admin/datatable/$table/view': {
      preLoaderRoute: typeof AuthAdminDatatableTableViewImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthHomeRoute,
    AuthAdminDatabaseRoute,
    AuthAdminDatatableTableAddRoute,
    AuthAdminDatatableTableEditRoute,
    AuthAdminDatatableTableViewRoute,
  ]),
  SignupRoute,
])

/* prettier-ignore-end */
